<a href="https://colab.research.google.com/github/Shubz15/Machine-Learning-Training/blob/main/Experiment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
arr = np.array([12, 18, 25, 30, 45, 50])
print("Array:", arr)



Array: [12 18 25 30 45 50]


In [4]:
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))
print("Standard Deviation:", np.std(arr))
print("Maximum Value:", np.max(arr))
print("Minimum Value:", np.min(arr))


Mean: 30.0
Sum: 180
Standard Deviation: 13.650396819628847
Maximum Value: 50
Minimum Value: 12


In [5]:
matrix = np.array([[1, 2, 3],
[4, 5, 6]])
print("Matrix:\n", matrix)
print("Matrix Shape:", matrix.shape)
print("Transpose:\n", matrix.T)


Matrix:
 [[1 2 3]
 [4 5 6]]
Matrix Shape: (2, 3)
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [6]:
import pandas as pd

In [7]:
data = {
"Name": ["Amit", "Rahul", "Sneha", "Pooja"],
"Marks": [85, 90, 88, 76],
"Age": [20, 21, 19, 22]
}
df = pd.DataFrame(data)
print(df)


    Name  Marks  Age
0   Amit     85   20
1  Rahul     90   21
2  Sneha     88   19
3  Pooja     76   22


In [8]:
print("Shape:", df.shape)
print("Columns:", df.columns)
print("Data Types:\n", df.dtypes)
print("Summary Statistics:\n", df.describe())

Shape: (4, 3)
Columns: Index(['Name', 'Marks', 'Age'], dtype='object')
Data Types:
 Name     object
Marks     int64
Age       int64
dtype: object
Summary Statistics:
            Marks        Age
count   4.000000   4.000000
mean   84.750000  20.500000
std     6.184658   1.290994
min    76.000000  19.000000
25%    82.750000  19.750000
50%    86.500000  20.500000
75%    88.500000  21.250000
max    90.000000  22.000000


In [9]:
print("Students with Marks > 80:\n", df[df["Marks"] > 80])
df["Grade"] = ["A", "A", "A", "B"]
print("Updated DataFrame:\n", df)


Students with Marks > 80:
     Name  Marks  Age
0   Amit     85   20
1  Rahul     90   21
2  Sneha     88   19
Updated DataFrame:
     Name  Marks  Age Grade
0   Amit     85   20     A
1  Rahul     90   21     A
2  Sneha     88   19     A
3  Pooja     76   22     B


In [11]:
from sklearn.datasets import load_iris
iris = load_iris()

In [12]:
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df["target"] = iris.target

In [13]:
print("Dataset Shape:", iris_df.shape)

Dataset Shape: (150, 5)


In [14]:
iris_df.info()
print("Summary Statistics:\n", iris_df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB
Summary Statistics:
        sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          

In [15]:
X = iris_df.iloc[:, :-1]
y = iris_df.iloc[:, -1]
print("Feature Matrix Shape:", X.shape)
print("Target Vector Shape:", y.shape)


Feature Matrix Shape: (150, 4)
Target Vector Shape: (150,)
