<a href="https://colab.research.google.com/github/Shubz15/Machine-Learning-Training/blob/main/Exp_6/Experiment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder


In [3]:
data = pd.read_csv("loan_approval_dataset.csv")
print("First 5 rows:")
print(data.head())
print("\nColumn Names:")
print(data.columns)
print("\nDataset Shape:")
print(data.shape)


First 5 rows:
   loan_id   no_of_dependents      education  self_employed   income_annum  \
0        1                  2       Graduate             No        9600000   
1        2                  0   Not Graduate            Yes        4100000   
2        3                  3       Graduate             No        9100000   
3        4                  3       Graduate             No        8200000   
4        5                  5   Not Graduate            Yes        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0           

In [4]:
le = LabelEncoder()
data[' education'] = le.fit_transform(data[' education'])
data[' self_employed'] = le.fit_transform(data[' self_employed'])
data[' loan_status'] = le.fit_transform(data[' loan_status'])
print("After Encoding:")
print(data.head())

After Encoding:
   loan_id   no_of_dependents   education   self_employed   income_annum  \
0        1                  2           0               0        9600000   
1        2                  0           1               1        4100000   
2        3                  3           0               0        9100000   
3        4                  3           0               0        8200000   
4        5                  5           1               1        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  176

In [5]:
data = data.drop('loan_id', axis=1)
print(data.columns)

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')


In [6]:
X = data.drop(' loan_status', axis=1)
Y = data[' loan_status']



In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(
 X, Y, test_size=0.2, random_state=42
)

In [8]:
dt_gini = DecisionTreeClassifier(criterion='gini')
dt_gini.fit(X_train, Y_train)
gini_pred = dt_gini.predict(X_test)
print("Decision Tree (Gini) Predictions:")
print(gini_pred[:10])
gini_acc = accuracy_score(Y_test, gini_pred)
print("Decision Tree (Gini) Accuracy:", gini_acc)


Decision Tree (Gini) Predictions:
[1 0 1 0 0 0 0 1 0 1]
Decision Tree (Gini) Accuracy: 0.9765807962529274


In [9]:
dt_entropy = DecisionTreeClassifier(criterion='entropy')
dt_entropy.fit(X_train, Y_train)
entropy_pred = dt_entropy.predict(X_test)
print("Decision Tree (Entropy) Predictions:")
print(entropy_pred[:10])
entropy_acc = accuracy_score(Y_test, entropy_pred)
print("Decision Tree (Entropy) Accuracy:", entropy_acc)

Decision Tree (Entropy) Predictions:
[1 0 1 0 0 0 0 1 0 1]
Decision Tree (Entropy) Accuracy: 0.9836065573770492


In [10]:
rf_model = RandomForestClassifier(n_estimators=100)
rf_model.fit(X_train, Y_train)
rf_pred = rf_model.predict(X_test)
print("Random Forest Predictions:")
print(rf_pred[:10])
rf_accuracy = accuracy_score(Y_test, rf_pred)
print("Random Forest Accuracy:", rf_accuracy)

Random Forest Predictions:
[1 0 1 0 0 0 0 1 0 1]
Random Forest Accuracy: 0.9789227166276346


In [11]:
print("\n--- Model Comparison ---")
print("Decision Tree (Gini):", gini_acc)
print("Decision Tree (Entropy):", entropy_acc)
print("Random Forest:", rf_accuracy)



--- Model Comparison ---
Decision Tree (Gini): 0.9765807962529274
Decision Tree (Entropy): 0.9836065573770492
Random Forest: 0.9789227166276346


In [12]:
new_data = [[2, 0, 0, 5000000, 15000000, 10, 699, 3000000, 2000000, 10000000, 4000000]]
new_data_df = pd.DataFrame(new_data, columns=X.columns)
prediction = rf_model.predict(new_data_df)
print("Prediction (0=Approved, 1=Rejected):", prediction[0])

Prediction (0=Approved, 1=Rejected): 0
